# current_llm_config: "llama3.1-8b-free"
current_llm_config: "reflection-70B"
keep_chat_history_when_changing_llms: True
# current_llm_config: "phi-3-med-free"
log_llm_prompts_to_file: True
use_llm_job_description_formatter: False
job_recon_style: verbose_bulk # either "json", "verbose", "verbose_bulk", or "off"
reset_llm_memory_between_questions: True
faqs:
  - "What is the job salary for this role?"
  - "What is the job location?"